import { Link } from "@tanstack/react-router";
import { ChevronDown, Edit3, Orbit, Share2 } from "lucide-react";
import type { CSSProperties } from "react";

import { Button } from "@/components/ui/button";
import { HOUSES, PLANET_BY_NUM, ZODIACS, formatDegree, thaiDate } from "@/lib/astro";
import type { ChartHouse, ChartPlanet, PlanetStandard } from "@/lib/astrology-engine.server";
import type { BirthProfileRow, NatalChartRow } from "@/lib/birth.functions";
import type { InterpretationSection } from "@/lib/interpretation";

export function AscendantRevealCard({ ascendant, houseSystem }: { ascendant: { signId: number; signTh: string; degree: number; minute: number }; houseSystem: string }) {
  const zodiac = ZODIACS.find((z) => z.id === ascendant.signId);
  return <section className="surface-hero grain mt-6 overflow-hidden p-5"><div className="grid grid-cols-[auto_minmax(0,1fr)] items-center gap-4"><div className="grid h-20 w-20 place-items-center rounded-full border border-primary/50 bg-primary/8 text-4xl text-primary shadow-[var(--shadow-glow)]">{zodiac?.symbol}</div><div className="min-w-0"><p className="eyebrow">Cosmic identity</p><h2 className="thai-heading text-gold truncate text-3xl">ลัคนา {ascendant.signTh}</h2><p className="mt-1 text-sm text-foreground/75">ราศีธาตุ{zodiac?.element} · {ascendant.degree ?? 0}°{String(ascendant.minute ?? 0).padStart(2,'0')}′</p></div></div><div className="my-5 h-px bg-linear-to-r from-transparent via-primary/40 to-transparent"/><p className="thai-heading text-lg text-foreground">{zodiac?.element === "ไฟ" ? "นักริเริ่มผู้ขับเคลื่อนด้วยแรงบันดาลใจ" : zodiac?.element === "ดิน" ? "นักสร้างผู้สุขุมและมั่นคง" : zodiac?.element === "ลม" ? "นักคิดผู้เชื่อมโยงโลกด้วยความเข้าใจ" : "ผู้รับรู้โลกด้วยความละเอียดอ่อน"}</p><p className="mt-2 text-[13px] leading-6 text-muted-foreground">การตีความจากลัคนาและธาตุราศีตามชุดกฎปัจจุบัน ไม่ใช่คำตัดสินตายตัว</p><div className="mt-4 inline-flex rounded-full border border-primary/20 px-3 py-1 text-[10px] text-primary">ระบบภพ {houseSystem === "whole_sign" ? "ราศีเต็ม" : houseSystem}</div></section>;
}

export function PlanetPositionGrid({ planets, onSelect }: { planets: ChartPlanet[]; onSelect: (planet: ChartPlanet) => void }) {
  return <section className="mt-8"><SectionHeading kicker="Nine planets" title="ตำแหน่งดาวทั้งเก้า"/><div className="grid grid-cols-2 gap-2.5 sm:grid-cols-3">{planets.map((p) => { const meta = PLANET_BY_NUM.get(p.num as 1); return <button key={p.num} onClick={() => onSelect(p)} className="planet-card press min-w-0 p-3 text-left"><div className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2"><span className="planet-sphere" style={{ "--planet-color": p.color } as CSSProperties}>{p.thaiNumeral}</span><div className="min-w-0"><h3 className="truncate text-sm font-medium text-foreground">{p.th}</h3><p className="truncate text-[11px] text-primary">{p.signTh} {formatDegree(p)}</p></div><span className="numeral text-xs text-primary">{p.thaiNumeral}</span></div><div className="mt-3 flex items-center justify-between text-[10px] text-muted-foreground"><span>{HOUSES[p.house - 1]?.th ?? `ภพ ${p.house}`}</span><span className={p.retrograde ? "text-destructive" : "text-success"}>{p.retrograde ? "พักร์" : "เดินหน้า"}</span></div><p className="mt-2 line-clamp-1 text-[10px] text-foreground/55">{meta?.meaning}</p></button>; })}</div></section>;
}

export function BirthDataCertificate({ profile, chart }: { profile: BirthProfileRow; chart: NatalChartRow }) {
  const facts = [["ชื่อ",profile.nickname],["วันเกิด",thaiDate(new Date(`${profile.birth_date}T12:00:00`))],["เวลาเกิด",profile.birth_time_known ? `${profile.birth_time?.slice(0,5)} น. · เวลาจริง` : "ไม่ทราบเวลา"],["UTC ที่ใช้",chart.utc_birth_datetime ? new Date(chart.utc_birth_datetime).toISOString() : "—"],["สถานที่",`${profile.province}, ${profile.country}`],["พิกัด",`${profile.latitude.toFixed(4)}, ${profile.longitude.toFixed(4)}`],["Timezone",profile.timezone],["เอนจิน",chart.engine_type],["เวอร์ชัน",chart.calculation_version],["Lahiri ayanamsha",chart.ayanamsa === null ? "—" : `${chart.ayanamsa.toFixed(4)}°`],["ระบบภพ",chart.house_system],["คำนวณเมื่อ",new Date(chart.calculated_at).toLocaleString("th-TH")]];
  return <section className="surface-card grain mt-8 p-5"><SectionHeading kicker="Birth certificate" title="ใบรับรองข้อมูลดวง"/><div className="grid grid-cols-2 gap-x-4 gap-y-4">{facts.map(([label,value]) => <div key={label} className="min-w-0 border-b border-primary/10 pb-3"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 break-words text-[12px] leading-5 text-foreground/85">{value}</p></div>)}</div><Button asChild variant="outline" className="mt-5 h-11 w-full rounded-xl border-primary/30"><Link to="/onboarding"><Edit3/>แก้ไขข้อมูลเกิด</Link></Button></section>;
}

export function NatalInterpretationSections({ sections }: { sections: InterpretationSection[] }) { return <section className="mt-8"><SectionHeading kicker="Thai astrology reading" title="คำอ่านดวงกำเนิด"/><div className="space-y-2">{sections.map((item,index) => <details key={item.title} open={index === 0} className="surface-card group p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-sm text-foreground"><span>{item.title}</span><ChevronDown className="h-4 w-4 shrink-0 text-primary transition-transform group-open:rotate-180"/></summary><div className="mt-4 border-t border-primary/12 pt-3"><p className="text-[10px] uppercase text-primary/75">ข้อมูลคำนวณ</p><p className="mt-1 text-[12px] text-foreground">{item.fact}</p><p className="mt-3 text-[10px] uppercase text-primary/75">คำตีความ</p><p className="mt-1 text-[13px] leading-6 text-foreground/75">{item.interpretation}</p></div></details>)}</div></section>; }

export function BirthChartActions({ onShare }: { onShare: () => void }) { return <section className="mt-8 grid gap-2"><Button asChild className="gold-metal h-13 rounded-xl text-sm"><Link to="/transits"><Orbit/>ดูดาวจร</Link></Button><div className="grid grid-cols-2 gap-2"><Button asChild variant="outline" className="h-11 rounded-xl"><Link to="/onboarding"><Edit3/>แก้ข้อมูลเกิด</Link></Button><Button asChild variant="outline" className="h-11 rounded-xl"><Link to="/ai-astrologer">คำทำนายเชิงลึก</Link></Button></div><Button variant="ghost" onClick={onShare} className="h-11 rounded-xl text-primary"><Share2/>แชร์ดวง</Button></section>; }

export function SectionHeading({ kicker, title }: { kicker: string; title: string }) { return <div className="mb-4"><p className="eyebrow">{kicker}</p><h2 className="thai-heading mt-1 text-xl text-foreground">{title}</h2></div>; }

export type { ChartHouse, PlanetStandard };