import { ChevronLeft, ChevronRight, Search } from "lucide-react";
import { useMemo, useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { KB_WORKFLOW } from "@/lib/kb-governance";

export type KnowledgeRow = Record<string, unknown> & { id: string };

export function KnowledgeTable({ rows, count, page, pageSize, search, status, loading, onPage, onSearch, onStatus, onOpenSource }: { rows: KnowledgeRow[]; count: number; page: number; pageSize: number; search: string; status: string; loading: boolean; onPage: (page: number) => void; onSearch: (value: string) => void; onStatus: (value: string) => void; onOpenSource?: (id: string) => void }) {
  const [selected, setSelected] = useState<KnowledgeRow | null>(null);
  const columns = useMemo(() => rows[0] ? Object.keys(rows[0]).filter((key) => key !== "id").slice(0, 6) : [], [rows]);
  const pages = Math.max(1, Math.ceil(count / pageSize));
  return <><section className="overflow-hidden rounded-md border border-border bg-card/45"><div className="grid gap-3 border-b border-border p-3 sm:grid-cols-[minmax(0,1fr)_180px_auto]"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input value={search} onChange={(event) => onSearch(event.target.value)} placeholder="ค้นหาชื่อ แหล่ง หรือรหัส…" className="pl-9"/></label><Select value={status} onValueChange={onStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">ทุกสถานะ</SelectItem>{KB_WORKFLOW.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Badge variant="outline" className="h-9 justify-center font-normal">{count.toLocaleString()} records</Badge></div><Table><TableHeader><TableRow>{columns.map((column) => <TableHead key={column} className="whitespace-nowrap text-[10px] uppercase">{column.replaceAll("_", " ")}</TableHead>)}</TableRow></TableHeader><TableBody>{loading ? <TableRow><TableCell colSpan={Math.max(columns.length,1)} className="h-36 text-center text-muted-foreground">กำลังโหลดข้อมูล…</TableCell></TableRow> : rows.length === 0 ? <TableRow><TableCell colSpan={Math.max(columns.length,1)} className="h-36 text-center text-muted-foreground">ไม่พบรายการ</TableCell></TableRow> : rows.map((row) => <TableRow key={row.id} className="cursor-pointer" onClick={() => { setSelected(row); onOpenSource?.(row.id); }}>{columns.map((column) => <TableCell key={column} className="max-w-64 truncate text-xs">{column === "status" || column.endsWith("_status") ? <StatusBadge value={String(row[column] ?? "—")}/> : formatValue(row[column])}</TableCell>)}</TableRow>)}</TableBody></Table><div className="flex items-center justify-between border-t border-border p-3"><p className="text-[10px] text-muted-foreground">หน้า {page} / {pages}</p><div className="flex gap-1"><Button variant="outline" size="icon" disabled={page <= 1} onClick={() => onPage(page - 1)} aria-label="หน้าก่อน"><ChevronLeft/></Button><Button variant="outline" size="icon" disabled={page >= pages} onClick={() => onPage(page + 1)} aria-label="หน้าถัดไป"><ChevronRight/></Button></div></div></section><Sheet open={Boolean(selected) && !onOpenSource} onOpenChange={(value) => { if (!value) setSelected(null); }}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>Record detail</SheetTitle><SheetDescription>รายละเอียดและ metadata ที่อ่านได้ตามสิทธิ์ของคุณ</SheetDescription></SheetHeader>{selected && <dl className="mt-6 space-y-3">{Object.entries(selected).map(([key,value]) => <div key={key} className="border-b border-border pb-3"><dt className="text-[10px] uppercase text-muted-foreground">{key.replaceAll("_", " ")}</dt><dd className="mt-1 break-words text-xs leading-5 text-foreground">{formatValue(value)}</dd></div>)}</dl>}</SheetContent></Sheet></>;
}

function StatusBadge({ value }: { value: string }) { const positive = value === "published" || value === "benchmark_verified" || value === "verified"; return <Badge variant="outline" className={positive ? "border-success/35 text-success" : value.includes("conflict") || value === "failed" ? "border-destructive/35 text-destructive" : "border-warning/35 text-warning"}>{value}</Badge>; }
function formatValue(value: unknown): string { if (value === null || value === undefined) return "—"; if (typeof value === "boolean") return value ? "ใช่" : "ไม่"; if (typeof value === "object") return JSON.stringify(value); return String(value); }