import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Clock3, Gift, ShieldAlert } from "lucide-react";
import QRCode from "qrcode";
import { useState } from "react";

import { AppShell, PageTransition } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { useWallet } from "@/hooks/useWallet";
import { createDayTransfer } from "@/lib/social.functions";

export const Route = createFileRoute("/_authenticated/gift-days")({ head: () => ({ meta: [
  { title: "โอนวันให้เพื่อน | Horathai AI" }, { name: "description", content: "สร้าง QR โอนวันส่วนที่เกิน 60 วัน อายุ 60 นาทีและใช้ได้ครั้งเดียว" },
  { property: "og:title", content: "โอนวันให้เพื่อน | Horathai AI" }, { property: "og:description", content: "แบ่งวันใช้งาน Horathai ให้เพื่อนผ่าน QR อย่างปลอดภัย" },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: GiftDaysPage });

function GiftDaysPage() { const { data } = useWallet(); const create = useServerFn(createDayTransfer); const transferable = Math.max(0, data.daysRemaining - 60); const [days, setDays] = useState(1); const [firstConfirm, setFirstConfirm] = useState(false); const [qr, setQr] = useState<string | null>(null); const [expiresAt, setExpiresAt] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const generate = async () => { setError(null); try { const result = await create({ data: { days } }); const url = `${window.location.origin}/transfer/${result.token}`; setQr(await QRCode.toDataURL(url, { width: 720, margin: 2, errorCorrectionLevel: "M" })); setExpiresAt(result.expiresAt); } catch (e) { setError(e instanceof Error ? e.message : "สร้าง QR ไม่สำเร็จ"); } }; return <AppShell><PageTransition><header><p className="eyebrow">Gift days</p><h1 className="display mt-1 text-2xl text-gold">โอนวันให้เพื่อน</h1><p className="mt-1 text-xs text-muted-foreground">โอนได้ {transferable.toLocaleString("th-TH")} วัน · ต้องเหลืออย่างน้อย 60 วัน</p></header>{qr ? <section className="surface-hero grain mt-5 p-6 text-center"><img src={qr} alt={`QR รับ ${days} วัน`} className="mx-auto aspect-square w-full max-w-72 rounded-lg"/><h2 className="thai-heading mt-4 text-xl text-gold">QR รับ {days} วัน</h2><p className="mt-2 flex items-center justify-center gap-2 text-[11px] text-muted-foreground"><Clock3 className="h-4 w-4"/> หมดอายุ {expiresAt ? new Intl.DateTimeFormat("th-TH", { timeStyle: "short" }).format(new Date(expiresAt)) : ""}</p><p className="mt-3 text-[10px] text-warning">ยังไม่หักวันจนกว่าเพื่อนจะยืนยันรับ</p></section> : <section className="surface-card mt-5 p-5"><Gift className="h-6 w-6 text-primary"/><label className="mt-4 block text-xs text-muted-foreground">จำนวนวันที่ต้องการโอน<input type="number" min={1} max={transferable} value={days} onChange={(event) => setDays(Number(event.target.value))} className="mt-2 h-12 w-full rounded-lg border border-border bg-muted/30 px-4 text-lg"/></label><div className="mt-4 rounded-xl border border-warning/25 bg-warning/8 p-4 text-[11px] leading-5 text-warning"><ShieldAlert className="mb-2 h-4 w-4"/> QR อายุ 60 นาที ใช้ครั้งเดียว เมื่อผู้รับยืนยันแล้วรายการจะย้อนกลับไม่ได้</div>{!firstConfirm ? <Button className="mt-5 h-12 w-full" disabled={days < 1 || days > transferable} onClick={() => setFirstConfirm(true)}>ตรวจสอบจำนวนวัน</Button> : <><p className="mt-5 text-center text-sm">ยืนยันสร้าง QR สำหรับ <strong className="text-gold">{days} วัน</strong>?</p><Button className="btn-gold mt-3 h-12 w-full" onClick={() => void generate()}>ยืนยันครั้งที่ 2 และสร้าง QR</Button><Button variant="ghost" className="mt-2 w-full" onClick={() => setFirstConfirm(false)}>แก้ไขจำนวน</Button></>}{error && <p className="mt-3 text-center text-xs text-destructive">{error}</p>}</section>}</PageTransition></AppShell>; }