/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedAiAstrologerRouteImport } from './routes/_authenticated/ai-astrologer'
import { Route as AuthenticatedBirthChartRouteImport } from './routes/_authenticated/birth-chart'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTransitsRouteImport } from './routes/_authenticated/transits'

const AuthenticatedAiAstrologerRoute =
  AuthenticatedAiAstrologerRouteImport.update({
    id: '/_authenticated/ai-astrologer',
    path: '/ai-astrologer',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBirthChartRoute = AuthenticatedBirthChartRouteImport.update({
  id: '/_authenticated/birth-chart',
  path: '/birth-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/_authenticated/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/_authenticated/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransitsRoute = AuthenticatedTransitsRouteImport.update({
  id: '/_authenticated/transits',
  path: '/transits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/ai-astrologer': typeof AuthenticatedAiAstrologerRoute
  '/birth-chart': typeof AuthenticatedBirthChartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transits': typeof AuthenticatedTransitsRoute
}
export interface FileRoutesByTo {
  '/ai-astrologer': typeof AuthenticatedAiAstrologerRoute
  '/birth-chart': typeof AuthenticatedBirthChartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transits': typeof AuthenticatedTransitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/ai-astrologer': typeof AuthenticatedAiAstrologerRoute
  '/_authenticated/birth-chart': typeof AuthenticatedBirthChartRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transits': typeof AuthenticatedTransitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ai-astrologer'
    | '/birth-chart'
    | '/dashboard'
    | '/onboarding'
    | '/premium'
    | '/settings'
    | '/transits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-astrologer'
    | '/birth-chart'
    | '/dashboard'
    | '/onboarding'
    | '/premium'
    | '/settings'
    | '/transits'
  id:
    | '__root__'
    | '/_authenticated/ai-astrologer'
    | '/_authenticated/birth-chart'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/premium'
    | '/_authenticated/settings'
    | '/_authenticated/transits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAiAstrologerRoute: typeof AuthenticatedAiAstrologerRoute
  AuthenticatedBirthChartRoute: typeof AuthenticatedBirthChartRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransitsRoute: typeof AuthenticatedTransitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/ai-astrologer': {
      id: '/_authenticated/ai-astrologer'
      path: '/ai-astrologer'
      fullPath: '/ai-astrologer'
      preLoaderRoute: typeof AuthenticatedAiAstrologerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/birth-chart': {
      id: '/_authenticated/birth-chart'
      path: '/birth-chart'
      fullPath: '/birth-chart'
      preLoaderRoute: typeof AuthenticatedBirthChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transits': {
      id: '/_authenticated/transits'
      path: '/transits'
      fullPath: '/transits'
      preLoaderRoute: typeof AuthenticatedTransitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAiAstrologerRoute: AuthenticatedAiAstrologerRoute,
  AuthenticatedBirthChartRoute: AuthenticatedBirthChartRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransitsRoute: AuthenticatedTransitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
