/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TransitRouteImport } from './routes/transit'
import { Route as AuthenticatedAiAstrologerRouteImport } from './routes/_authenticated/ai-astrologer'
import { Route as AuthenticatedBirthChartRouteImport } from './routes/_authenticated/birth-chart'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKnowledgeAdminRouteImport } from './routes/_authenticated/knowledge-admin'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTransitsRouteImport } from './routes/_authenticated/transits'
import { Route as AuthenticatedKnowledgeAdminIndexRouteImport } from './routes/_authenticated/knowledge-admin.index'
import { Route as AuthenticatedKnowledgeAdminEntityRouteImport } from './routes/_authenticated/knowledge-admin.$entity'
import { Route as AuthenticatedKnowledgeAdminSourcesSourceIdRouteImport } from './routes/_authenticated/knowledge-admin.sources.$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitRoute = TransitRouteImport.update({
  id: '/transit',
  path: '/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiAstrologerRoute =
  AuthenticatedAiAstrologerRouteImport.update({
    id: '/ai-astrologer',
    path: '/ai-astrologer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBirthChartRoute = AuthenticatedBirthChartRouteImport.update({
  id: '/birth-chart',
  path: '/birth-chart',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeAdminRoute =
  AuthenticatedKnowledgeAdminRouteImport.update({
    id: '/knowledge-admin',
    path: '/knowledge-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransitsRoute = AuthenticatedTransitsRouteImport.update({
  id: '/transits',
  path: '/transits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeAdminIndexRoute =
  AuthenticatedKnowledgeAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKnowledgeAdminRoute,
  } as any)
const AuthenticatedKnowledgeAdminEntityRoute =
  AuthenticatedKnowledgeAdminEntityRouteImport.update({
    id: '/$entity',
    path: '/$entity',
    getParentRoute: () => AuthenticatedKnowledgeAdminRoute,
  } as any)
const AuthenticatedKnowledgeAdminSourcesSourceIdRoute =
  AuthenticatedKnowledgeAdminSourcesSourceIdRouteImport.update({
    id: '/sources/$sourceId',
    path: '/sources/$sourceId',
    getParentRoute: () => AuthenticatedKnowledgeAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/chart': typeof ChartRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/transit': typeof TransitRoute
  '/ai-astrologer': typeof AuthenticatedAiAstrologerRoute
  '/birth-chart': typeof AuthenticatedBirthChartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/knowledge-admin': typeof AuthenticatedKnowledgeAdminRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transits': typeof AuthenticatedTransitsRoute
  '/knowledge-admin/$entity': typeof AuthenticatedKnowledgeAdminEntityRoute
  '/knowledge-admin/': typeof AuthenticatedKnowledgeAdminIndexRoute
  '/knowledge-admin/sources/$sourceId': typeof AuthenticatedKnowledgeAdminSourcesSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/chart': typeof ChartRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/transit': typeof TransitRoute
  '/ai-astrologer': typeof AuthenticatedAiAstrologerRoute
  '/birth-chart': typeof AuthenticatedBirthChartRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transits': typeof AuthenticatedTransitsRoute
  '/knowledge-admin/$entity': typeof AuthenticatedKnowledgeAdminEntityRoute
  '/knowledge-admin': typeof AuthenticatedKnowledgeAdminIndexRoute
  '/knowledge-admin/sources/$sourceId': typeof AuthenticatedKnowledgeAdminSourcesSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ai': typeof AiRoute
  '/chart': typeof ChartRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/transit': typeof TransitRoute
  '/_authenticated/ai-astrologer': typeof AuthenticatedAiAstrologerRoute
  '/_authenticated/birth-chart': typeof AuthenticatedBirthChartRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/knowledge-admin': typeof AuthenticatedKnowledgeAdminRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transits': typeof AuthenticatedTransitsRoute
  '/_authenticated/knowledge-admin/$entity': typeof AuthenticatedKnowledgeAdminEntityRoute
  '/_authenticated/knowledge-admin/': typeof AuthenticatedKnowledgeAdminIndexRoute
  '/_authenticated/knowledge-admin/sources/$sourceId': typeof AuthenticatedKnowledgeAdminSourcesSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/chart'
    | '/privacy'
    | '/terms'
    | '/transit'
    | '/ai-astrologer'
    | '/birth-chart'
    | '/dashboard'
    | '/knowledge-admin'
    | '/onboarding'
    | '/premium'
    | '/settings'
    | '/transits'
    | '/knowledge-admin/$entity'
    | '/knowledge-admin/'
    | '/knowledge-admin/sources/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/chart'
    | '/privacy'
    | '/terms'
    | '/transit'
    | '/ai-astrologer'
    | '/birth-chart'
    | '/dashboard'
    | '/onboarding'
    | '/premium'
    | '/settings'
    | '/transits'
    | '/knowledge-admin/$entity'
    | '/knowledge-admin'
    | '/knowledge-admin/sources/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai'
    | '/chart'
    | '/privacy'
    | '/terms'
    | '/transit'
    | '/_authenticated/ai-astrologer'
    | '/_authenticated/birth-chart'
    | '/_authenticated/dashboard'
    | '/_authenticated/knowledge-admin'
    | '/_authenticated/onboarding'
    | '/_authenticated/premium'
    | '/_authenticated/settings'
    | '/_authenticated/transits'
    | '/_authenticated/knowledge-admin/$entity'
    | '/_authenticated/knowledge-admin/'
    | '/_authenticated/knowledge-admin/sources/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AiRoute: typeof AiRoute
  ChartRoute: typeof ChartRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TransitRoute: typeof TransitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transit': {
      id: '/transit'
      path: '/transit'
      fullPath: '/transit'
      preLoaderRoute: typeof TransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-astrologer': {
      id: '/_authenticated/ai-astrologer'
      path: '/ai-astrologer'
      fullPath: '/ai-astrologer'
      preLoaderRoute: typeof AuthenticatedAiAstrologerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/birth-chart': {
      id: '/_authenticated/birth-chart'
      path: '/birth-chart'
      fullPath: '/birth-chart'
      preLoaderRoute: typeof AuthenticatedBirthChartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge-admin': {
      id: '/_authenticated/knowledge-admin'
      path: '/knowledge-admin'
      fullPath: '/knowledge-admin'
      preLoaderRoute: typeof AuthenticatedKnowledgeAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transits': {
      id: '/_authenticated/transits'
      path: '/transits'
      fullPath: '/transits'
      preLoaderRoute: typeof AuthenticatedTransitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge-admin/': {
      id: '/_authenticated/knowledge-admin/'
      path: '/'
      fullPath: '/knowledge-admin/'
      preLoaderRoute: typeof AuthenticatedKnowledgeAdminIndexRouteImport
      parentRoute: typeof AuthenticatedKnowledgeAdminRoute
    }
    '/_authenticated/knowledge-admin/$entity': {
      id: '/_authenticated/knowledge-admin/$entity'
      path: '/$entity'
      fullPath: '/knowledge-admin/$entity'
      preLoaderRoute: typeof AuthenticatedKnowledgeAdminEntityRouteImport
      parentRoute: typeof AuthenticatedKnowledgeAdminRoute
    }
    '/_authenticated/knowledge-admin/sources/$sourceId': {
      id: '/_authenticated/knowledge-admin/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/knowledge-admin/sources/$sourceId'
      preLoaderRoute: typeof AuthenticatedKnowledgeAdminSourcesSourceIdRouteImport
      parentRoute: typeof AuthenticatedKnowledgeAdminRoute
    }
  }
}

interface AuthenticatedKnowledgeAdminRouteChildren {
  AuthenticatedKnowledgeAdminEntityRoute: typeof AuthenticatedKnowledgeAdminEntityRoute
  AuthenticatedKnowledgeAdminIndexRoute: typeof AuthenticatedKnowledgeAdminIndexRoute
  AuthenticatedKnowledgeAdminSourcesSourceIdRoute: typeof AuthenticatedKnowledgeAdminSourcesSourceIdRoute
}

const AuthenticatedKnowledgeAdminRouteChildren: AuthenticatedKnowledgeAdminRouteChildren =
  {
    AuthenticatedKnowledgeAdminEntityRoute:
      AuthenticatedKnowledgeAdminEntityRoute,
    AuthenticatedKnowledgeAdminIndexRoute:
      AuthenticatedKnowledgeAdminIndexRoute,
    AuthenticatedKnowledgeAdminSourcesSourceIdRoute:
      AuthenticatedKnowledgeAdminSourcesSourceIdRoute,
  }

const AuthenticatedKnowledgeAdminRouteWithChildren =
  AuthenticatedKnowledgeAdminRoute._addFileChildren(
    AuthenticatedKnowledgeAdminRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiAstrologerRoute: typeof AuthenticatedAiAstrologerRoute
  AuthenticatedBirthChartRoute: typeof AuthenticatedBirthChartRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKnowledgeAdminRoute: typeof AuthenticatedKnowledgeAdminRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransitsRoute: typeof AuthenticatedTransitsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiAstrologerRoute: AuthenticatedAiAstrologerRoute,
  AuthenticatedBirthChartRoute: AuthenticatedBirthChartRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKnowledgeAdminRoute:
    AuthenticatedKnowledgeAdminRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransitsRoute: AuthenticatedTransitsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AiRoute: AiRoute,
  ChartRoute: ChartRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TransitRoute: TransitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
